### ISSUE TITLE
Code Improvement Suggestions

### ISSUE THREAD

**Issue by aima98** [Ferizad/Portfolio#4]
- Using h2 instead of h1 for subtitles because the h1 tag should be used once given indicates what the most important text on a page is. It is usually the most visually notable content on the page, and enhances clarity for the reader. It's also important for search engine optimization (SEO).
- In the class of cards, the padding 10px 10px 10px 10px should be changed to just only 10px.
- For the Get in Touch button, Changing it from input to button.
- Removing the font-family from the other elements as it has been already in universal selector. The universal selector (*) will select all the element on the document

**Comment by Ferizad** [comment]
✅All suggestions were reviewed and added respectively.
